#!/usr/bin/env bash
# Install a health-monitored LiteLLM proxy service for the 1M vLLM stack.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="${SERVICE_NAME:-deepseek-v4-flash-1m-litellm}"
VLLM_SERVICE_NAME="${VLLM_SERVICE_NAME:-deepseek-v4-flash-1m}"
SERVICE_USER="${SERVICE_USER:-$USER}"
SERVICE_GROUP="${SERVICE_GROUP:-$SERVICE_USER}"
SERVICE_HOME="${SERVICE_HOME:-$HOME}"
REPO_DIR="${REPO_DIR:-$SCRIPT_DIR}"
LITELLM_CONTAINER_NAME="${LITELLM_CONTAINER_NAME:-deepseek-v4-flash-1m-litellm}"
LITELLM_IMAGE="${LITELLM_IMAGE:-ghcr.io/berriai/litellm:main-latest}"
LITELLM_PORT="${LITELLM_PORT:-4000}"
LITELLM_MASTER_KEY="${LITELLM_MASTER_KEY:-sk-local-vllm}"
SERVICE_RESTART_SEC="${SERVICE_RESTART_SEC:-10}"
SERVICE_START_LIMIT_BURST="${SERVICE_START_LIMIT_BURST:-20}"
SERVICE_START_LIMIT_INTERVAL="${SERVICE_START_LIMIT_INTERVAL:-1800}"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

require sudo
require docker
require systemctl

sudo_run() {
  if sudo -n true 2>/dev/null; then
    sudo -n "$@"
  elif [[ -n "${SUDO_ASKPASS:-}" ]]; then
    sudo -A "$@"
  else
    sudo -n "$@"
  fi
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

config="$tmpdir/config.yaml"
env_file="$tmpdir/${SERVICE_NAME}.default"
launcher="$tmpdir/${SERVICE_NAME}-launch"
unit="$tmpdir/${SERVICE_NAME}.service"

cp "${SCRIPT_DIR}/litellm-config.yaml" "$config"

cat > "$env_file" <<EOF
# Generated by install-litellm-service.sh
REPO_DIR=${REPO_DIR}
LITELLM_CONTAINER_NAME=${LITELLM_CONTAINER_NAME}
LITELLM_IMAGE=${LITELLM_IMAGE}
LITELLM_PORT=${LITELLM_PORT}
LITELLM_CONFIG=/etc/litellm/${SERVICE_NAME}/config.yaml
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
LITELLM_MODEL_NAME=deepseek-v4-flash
VLLM_HEALTH_URL=http://127.0.0.1:8000/v1/models
LITELLM_HEALTH_URL=http://127.0.0.1:${LITELLM_PORT}/v1/models
LITELLM_LIVENESS_URL=http://127.0.0.1:${LITELLM_PORT}/health/liveliness
VLLM_STARTUP_TIMEOUT_SEC=3600
HEALTH_INTERVAL_SEC=30
HEALTH_FAILURES=4
EOF

cp "${SCRIPT_DIR}/cluster-litellm-launch.sh" "$launcher"
chmod 755 "$launcher"

cat > "$unit" <<EOF
[Unit]
Description=LiteLLM proxy for DeepSeek V4 Flash 1M (MiaAI-Lab)
Documentation=https://github.com/MiaAI-Lab/DeepSeek-V4-Flash-Dual-DGX-Spark-1M-Context
Wants=network-online.target docker.service ${VLLM_SERVICE_NAME}.service
After=network-online.target docker.service ${VLLM_SERVICE_NAME}.service
StartLimitIntervalSec=${SERVICE_START_LIMIT_INTERVAL}
StartLimitBurst=${SERVICE_START_LIMIT_BURST}

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${REPO_DIR}
Environment=HOME=${SERVICE_HOME}
Environment=SERVICE_ENV=/etc/default/${SERVICE_NAME}
EnvironmentFile=-/etc/default/${SERVICE_NAME}
ExecStart=/usr/local/bin/${SERVICE_NAME}-launch
Restart=on-failure
RestartSec=${SERVICE_RESTART_SEC}
TimeoutStartSec=0
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
EOF

sudo_run install -d -m 0755 "/etc/litellm/${SERVICE_NAME}"
sudo_run install -m 0644 "$config" "/etc/litellm/${SERVICE_NAME}/config.yaml"
sudo_run install -m 0600 "$env_file" "/etc/default/${SERVICE_NAME}"
sudo_run install -m 0755 "$launcher" "/usr/local/bin/${SERVICE_NAME}-launch"
sudo_run install -m 0644 "$unit" "/etc/systemd/system/${SERVICE_NAME}.service"
sudo_run systemctl daemon-reload
sudo_run systemctl enable "${SERVICE_NAME}.service"

printf 'Installed and enabled %s.service\n' "$SERVICE_NAME"
printf 'Start now:   sudo systemctl start %s.service\n' "$SERVICE_NAME"
printf 'Check logs:  journalctl -u %s.service -f\n' "$SERVICE_NAME"
printf 'Endpoint:    http://127.0.0.1:%s/v1  (key: %s)\n' "$LITELLM_PORT" "$LITELLM_MASTER_KEY"
