#!/usr/bin/env bash
# Install persistent GB10 GPU graphics clock cap (forum 372662: -lgc 0,2000).
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"
SERVICE_NAME="${SERVICE_NAME:-nvidia-gpu-clock-cap}"
GPU_CLOCK_MAX_MHZ="${GPU_CLOCK_MAX_MHZ:-2000}"
GPU_STARTUP_DELAY_SEC="${GPU_STARTUP_DELAY_SEC:-5}"
REMOTE_USER="${REMOTE_USER:-linar}"
WORKER_HOST="${WORKER_HOST:-192.168.0.127}"
NODE3_HOST="${NODE3_HOST:-192.168.0.36}"
INSTALL_NODE3="${INSTALL_NODE3:-0}"
LOCAL_ONLY="${LOCAL_ONLY:-0}"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

sudo_run() {
  if sudo -n true 2>/dev/null; then
    sudo -n "$@"
  elif [[ -n "${SUDO_ASKPASS:-}" ]]; then
    sudo -A "$@"
  else
    sudo -n "$@"
  fi
}

install_on_host() {
  require systemctl
  require nvidia-smi

  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' RETURN

  local env_file="${tmpdir}/${SERVICE_NAME}.default"
  local unit_file="${tmpdir}/${SERVICE_NAME}.service"

  cat >"$env_file" <<EOF
# Generated by install-gpu-clock-cap.sh
GPU_CLOCK_MAX_MHZ=${GPU_CLOCK_MAX_MHZ}
GPU_STARTUP_DELAY_SEC=${GPU_STARTUP_DELAY_SEC}
EOF

  cat >"$unit_file" <<EOF
[Unit]
Description=Cap NVIDIA GPU graphics clock (GB10 power/temp tuning)
Documentation=https://forums.developer.nvidia.com/t/cooler-gb10-temps-almost-no-performance-lost/372662
After=nvidia-persistenced.service
Wants=nvidia-persistenced.service

[Service]
Type=oneshot
EnvironmentFile=-/etc/default/${SERVICE_NAME}
ExecStart=/usr/bin/bash -c 'sleep \${GPU_STARTUP_DELAY_SEC:-5} && nvidia-smi -pm 1 && nvidia-smi -lgc 0,\${GPU_CLOCK_MAX_MHZ:-2000} && echo "GPU clock cap: \${GPU_CLOCK_MAX_MHZ:-2000} MHz"'
ExecStop=/usr/bin/bash -c 'nvidia-smi -rgc || true'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

  sudo_run install -m 0644 "$env_file" "/etc/default/${SERVICE_NAME}"
  sudo_run install -m 0644 "$unit_file" "/etc/systemd/system/${SERVICE_NAME}.service"
  sudo_run systemctl daemon-reload
  sudo_run systemctl enable "${SERVICE_NAME}.service"
  sudo_run systemctl restart "${SERVICE_NAME}.service"

  echo "Installed ${SERVICE_NAME}.service on $(hostname) (max ${GPU_CLOCK_MAX_MHZ} MHz)"
  nvidia-smi --query-gpu=clocks.current.graphics,clocks.max.graphics,power.draw,temperature.gpu \
    --format=csv,noheader
}

install_remote() {
  local host="$1"
  echo "=== Installing on ${REMOTE_USER}@${host} ==="
  ssh -o BatchMode=yes -o ConnectTimeout=10 "${REMOTE_USER}@${host}" \
    "GPU_CLOCK_MAX_MHZ=${GPU_CLOCK_MAX_MHZ} GPU_STARTUP_DELAY_SEC=${GPU_STARTUP_DELAY_SEC} LOCAL_ONLY=1 bash -s" \
    <"${SCRIPT_DIR}/install-gpu-clock-cap.sh"
}

if [[ "${LOCAL_ONLY}" == "1" ]]; then
  require sudo
  install_on_host
  exit 0
fi

require sudo
install_on_host
install_remote "$WORKER_HOST"
if [[ "$INSTALL_NODE3" == "1" ]]; then
  install_remote "$NODE3_HOST"
fi

echo "GPU clock cap active on cluster inference nodes."
