#!/usr/bin/env bash
# Install a systemd service for DeepSeek V4 Flash 1M (MiaAI-Lab recipe).
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SERVICE_NAME="${SERVICE_NAME:-deepseek-v4-flash-1m}"
SERVICE_USER="${SERVICE_USER:-$USER}"
SERVICE_GROUP="${SERVICE_GROUP:-$SERVICE_USER}"
SERVICE_HOME="${SERVICE_HOME:-$HOME}"
REPO_DIR="${REPO_DIR:-$SCRIPT_DIR}"
REMOTE_USER="${REMOTE_USER:-$SERVICE_USER}"
WORKER_HOST="${WORKER_HOST:-192.168.0.127}"
WORKER_DIR="${WORKER_DIR:-agent/deepseek-v4-flash-1m-context}"
SERVICE_RESTART_SEC="${SERVICE_RESTART_SEC:-30}"
SERVICE_START_LIMIT_BURST="${SERVICE_START_LIMIT_BURST:-20}"
SERVICE_START_LIMIT_INTERVAL="${SERVICE_START_LIMIT_INTERVAL:-1800}"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

require sudo
require systemctl

sudo_run() {
  if sudo -n true 2>/dev/null; then
    sudo -n "$@"
  elif [[ -n "${SUDO_ASKPASS:-}" ]]; then
    sudo -A "$@"
  else
    sudo -n "$@"
  fi
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

env_file="$tmpdir/${SERVICE_NAME}.default"
launcher="$tmpdir/${SERVICE_NAME}-launch"
unit="$tmpdir/${SERVICE_NAME}.service"

cat > "$env_file" <<EOF
# Generated by install-systemd-service.sh
REPO_DIR=${REPO_DIR}
REMOTE_USER=${REMOTE_USER}
CLUSTER_NNODES=2
WORKER_HOST=${WORKER_HOST}
NODE3_HOST=192.168.0.36
WORKER_QSFP_IP=192.168.179.127
NODE3_QSFP_IP=192.168.177.36
HEAD_QSFP_IP_WORKER=192.168.179.27
HEAD_QSFP_IP_NODE3=192.168.177.27
REMOTE_DIR=${WORKER_DIR}
CONTAINER_NAME=vllm_dsf1m_prod
SERVED_MODEL_NAME=deepseek-v4-flash
HEALTH_URL=http://127.0.0.1:8000/v1/models
HEALTH_INTERVAL_SEC=30
HEALTH_FAILURES=4
STARTUP_TIMEOUT_SEC=5400
WORKER_STAGGER_SEC=45
MIN_CUDA_FREE_GB=100
MAX_LAUNCH_ATTEMPTS=3
ROCE_WAIT_SEC=300
EOF

cp "${SCRIPT_DIR}/cluster-launch.sh" "$launcher"
chmod 755 "$launcher"

cat > "$unit" <<EOF
[Unit]
Description=DeepSeek V4 Flash 1M dual Spark vLLM (MiaAI-Lab)
Documentation=https://github.com/MiaAI-Lab/DeepSeek-V4-Flash-Dual-DGX-Spark-1M-Context
Wants=network-online.target docker.service
After=network-online.target docker.service
StartLimitIntervalSec=${SERVICE_START_LIMIT_INTERVAL}
StartLimitBurst=${SERVICE_START_LIMIT_BURST}

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${REPO_DIR}
Environment=HOME=${SERVICE_HOME}
Environment=SERVICE_ENV=/etc/default/${SERVICE_NAME}
EnvironmentFile=-/etc/default/${SERVICE_NAME}
ExecStart=/usr/local/bin/${SERVICE_NAME}-launch
Restart=on-failure
RestartSec=${SERVICE_RESTART_SEC}
TimeoutStartSec=0
KillSignal=SIGINT

[Install]
WantedBy=multi-user.target
EOF

sudo_run install -m 0644 "$env_file" "/etc/default/${SERVICE_NAME}"
sudo_run install -m 0755 "$launcher" "/usr/local/bin/${SERVICE_NAME}-launch"
sudo_run install -m 0644 "$unit" "/etc/systemd/system/${SERVICE_NAME}.service"
sudo_run systemctl daemon-reload
sudo_run systemctl enable "${SERVICE_NAME}.service"

printf 'Installed and enabled %s.service\n' "$SERVICE_NAME"
printf 'Start now:   sudo systemctl start %s.service\n' "$SERVICE_NAME"
printf 'Check logs:  journalctl -u %s.service -f\n' "$SERVICE_NAME"
